# Generated by Django 2.2.6 on 2019-11-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessenge',
            fields=[
            ],
        ),
    ]
