# Generated by Django 2.2.6 on 2019-11-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMessenge',
            new_name='GroupMessage',
        ),
    ]
